### PR TITLE
added license file

### PR DESCRIPTION
**Pull request by cvasilak**
@corinnekrych mind to quick look at?

### CODE REVIEW

**Comment by corinnekrych** [comment]
@cvasilak just wondering why not reusing https://github.com/aerogear/aerogear-ios/blob/1.6.x/LICENSE ?

**Comment by cvasilak** [comment]
@corinnekrych no preference tbh  @matzew wdyt?

**Comment by matzew** [comment]
what ever is the easiest. this is trivial stuff ;-)

On Mon, Jan 12, 2015 at 5:05 PM, Christos Vasilakis <
notifications@github.com> wrote:

> @corinnekrych <https://github.com/corinnekrych> no preference tbh @matzew
> <https://github.com/matzew> wdyt?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aerogear/aerogear-ios-http/pull/30#issuecomment-69593313>
> .
>



-- 
Matthias Wessendorf

blog: http://matthiaswessendorf.wordpress.com/
sessions: http://www.slideshare.net/mwessendorf
twitter: http://twitter.com/mwessendorf

**Comment by abstractj** [comment]
@cvasilak @matzew @corinnekrych the LICENSE file just refer to the header necessary in all files on AeroGear, it refer to the props for JBoss/Red Hat.

This file added by @cvasilak IMO refers to ASL2, which is the informative necessary to let people know which kind of license the project make use of. Which is a pattern in most of our repositories.

**Comment by matzew** [comment]
@abstractj Oh, I just see the content of the "old" file (https://github.com/aerogear/aerogear-ios/blob/1.6.x/LICENSE) is the full license (but thought it was).

so yeah, the one proposed w/ this PR should be used

**Comment by matzew** [comment]
merging....

**Comment by matzew** [comment]
thanks @cvasilak! landed on https://github.com/aerogear/aerogear-ios-http/commit/869e7bd71d54cea9b989e9b82df98b862a28e913

:tada:

**Pull request closed without merging**
