### PR TITLE
Updated for Xcode 8, Swift 2.3 and Carthage Support

### PR DESCRIPTION
**Pull request by colemancda**

### CODE REVIEW

**Comment by danielpassos** [comment]
Hey @colemancda Thank you for the contribution. Can you give me some favors?

1. Remove _[claudioredi]_ from the commit messages
1. Cherry-pick the 3 _Improved invalid token handling_ commits in only one
1. Rebase

**Comment by danielpassos** [comment]
@corinnekrych wdyt? Still valid?

**Comment by corinnekrych** [comment]
@danielpassos to answer your question indetails:
- the Swift2.3 support was release in 0.8.0 with Xcode 8 => outdated
- carthage support: we still don't have it.It would be nice to have it and still keep CocoaPods. => we could cherry pick (if feasible) we have a [AGIOS-415](https://issues.jboss.org/browse/AGIOS-415) to track it.
- handling self-signed cert commit bring an interesting discussion we should be more flexible and provide hook in the lib to handle authentication challenge to cater for this: https://github.com/aerogear/aerogear-ios-http/pull/73/commits/76dae3175eb62c815e1a46eec6159d0cb973a0ee => need to be revisited [AGIOS-526](https://issues.jboss.org/browse/AGIOS-526) to log it.
- watchOS, tvOS target could be added => cherry pick
We could close the PR for now and cherry pick as we do separate ticket, wdyt?

**Comment by corinnekrych** [comment]
Closing the ticket for now.
@colemancda if you can provide more fine-grained PR. I'd ❤️ it

**Pull request closed without merging**
