### PR TITLE
Swift 2.0

### PR DESCRIPTION
**Pull request by corinnekrych**
AGIOS-456 support for Swift2-0 and Xcode7.

### CODE REVIEW

**Comment by danielpassos** [comment]
@corinnekrych How can I test it? I ran the same test of [travis-ci](https://travis-ci.org/aerogear/aerogear-ios-http/builds/81599002) 

```
xcodebuild -workspace AeroGearHttp.xcworkspace -scheme AeroGearHttpTests -sdk iphonesimulator -destination "OS=8.4,name=iPhone 6 Plus" -configuration Release clean test
```

and got the same error:

```
Testing failed:
	'advance' is unavailable: call the 'advancedBy(n)' method on the index
	'join' is unavailable: call the 'joinWithSeparator()' method on the sequence of elements
	'extend' has been renamed to 'appendContentsOf'
	'extend' has been renamed to 'appendContentsOf'
```

**Comment by corinnekrych** [comment]
@danielpassos mmm... it seems to be a beat6 changes
it uses to be ok in beta5
let me look into this compilation issue

**Comment by corinnekrych** [comment]
@danielpassos see: http://stackoverflow.com/questions/32216817/how-to-use-distanceto-advancedby-to-handle-string-in-xcode7-beta6 for more details

**Comment by danielpassos** [comment]
:+1:

**Pull request merged**
