### PR TITLE
Convert AeroGearHttp Test scheme to Integration Tests scheme

### PR DESCRIPTION
**Pull request by cvasilak**
this PR adds an 'IntegrationTests' target that enables tests to be run within the context of the emulator. Details of why this was required can be found on our JIRA [AGIOS-330](https://issues.jboss.org/browse/AGIOS-330)

To test:
After running ```pod install``` and opening the workspace, choose ```IntegrationTest``` schema, and then choose  ```Product->Test```. Tests should run and succeed.

@corinnekrych @danbev mind to have a look?

### CODE REVIEW

**Comment by corinnekrych** [comment]
@cvasilak Rather than making all tests integration tests, i think we should have most of them in unit tests using httpstub to mock http layer(like we used to). I've created a JIRA for that:
AGIOS-328
Also be caution about AeroGearHttp.xcodeproj/project.pbxproj going xml format makes it difficult to track changes.

**Comment by cvasilak** [comment]
@corinnekrych +9001 that's exactly the reason as you stated, so we are now free to separate our tests:

a) Unit Tests (with httpstub mock) go to the default  ```AeroGearHttp test target``` and 
b) integrations tests (that this PR is) go to ```IntegrationTests target``` and since the tests are really integration tests and require a running emulator for some services to be available plus network access. Unless you mean getting rid of the existing tests and going only with unit tests with mocking which I am -1 tbh

I think that is clean and visible separation, wdyt?

**Comment by corinnekrych** [comment]
@cvasilak most of those tests could/should be unit tests. AGIOS-328 purpose is to bring them back to unit tests. So I'm -1 migrating them to int. tests because then we have only integration tests and no unit tests.
Let's move them to unit tests, then we can add one test suite for integrstion test. Unit tests are the base of pyramid. 
I'd rather close the PR for now and revisit once we've got most of the test unit tests.

**Comment by danbev** [comment]
@cvasilak @corinnekrych Should I still do a review or hold off?

**Comment by cvasilak** [comment]
thank you @danbev!

mind to hold off for a bit, we will have a discussion with @corinnekrych about it and will update this PR accordingly.

**Comment by cvasilak** [comment]
as discussed closing this PR.

a way to introduce unit tests with mocks plus coexisting with the integration test target schema that this PR introduces would be possible different and would be discussed on the ML.

**Pull request closed without merging**
