### PR TITLE
Update to Xcode 8 / Swift 2.3

### PR DESCRIPTION
**Pull request by tuzonghua**
A number of small changes to bring the Http library in compliance with latest Xcode 8 and Swift 2.3.

### CODE REVIEW

**Comment by danielpassos** [comment]
Hi @tuzonghua 

First of all, sorry for my late reply. I have a quick questions.

1) Any idea why tests it failling?
2) There is any reason to use `1.1.0.beta.1`?

**Comment by tuzonghua** [comment]
@danielpassos Travis is having issues outside of the written unit tests. Try running the tests within Xcode and ask @corinnekrych about her struggle with Travis. As for the CP version, there's no real need besides wanting to stay current with the project (and also because it's the version I'm running ;) ).

**Comment by corinnekrych** [comment]
@danielpassos cocoapods 1.1.0.beta1 is required to make sure SWIFT_VERSION OHHTTPStubs is set to 2.3 see:
https://github.com/CocoaPods/CocoaPods/pull/5540

@tuzonghua to allow both compatibility with Xcode7(Swift2.2) and Xcode8(Swift2.3) I like the usage of:
```
#if swift(>=2.3)
// this compiles on Xcode 8 / Swift 2.3 / iOS 10
#else
// this compiles on Xcode 7 / Swift 2.2 / iOS 9
#endif 
```
Let me do a PR based on your commit with this addition and then merge.

**Comment by corinnekrych** [comment]
@tuzonghua closing this one in favor of https://github.com/aerogear/aerogear-ios-http/pull/71
which contain all your fixes

**Pull request merged**
